local mod = GreedSpecialRooms

mod.enum.rooms = {
	[RoomType.ROOM_ARCADE] = {
        {id = 0, weight = 1},
        {id = 1, weight = 1},
        {id = 2, weight = 1},
        {id = 3, weight = 1},
        {id = 4, weight = 1},
        {id = 5, weight = 1},
        {id = 6, weight = 1},
        {id = 7, weight = 1},
        {id = 8, weight = .5},
        {id = 9, weight = 1},
        {id = 10, weight = 1},
        {id = 11, weight = 1},
        {id = 12, weight = 1},
        {id = 13, weight = 1},
        {id = 14, weight = 1},
        {id = 15, weight = 1},
        {id = 16, weight = .5},
        {id = 17, weight = 1},
        {id = 18, weight = 1},
        {id = 19, weight = .1},
        {id = 20, weight = .1},
        {id = 21, weight = 1},
        {id = 22, weight = 1},
        {id = 23, weight = 1},
        {id = 24, weight = 1},
        {id = 25, weight = .5},
        {id = 26, weight = .25},
        {id = 27, weight = 1},
        {id = 28, weight = .25},
        {id = 29, weight = 1},
        {id = 30, weight = 1},
        {id = 31, weight = .5},
        {id = 32, weight = .5}
	},
	--Cain Arcade
	[RoomType.ROOM_ARCADE + 100] = {
        {id = 41, weight = 1},
        {id = 42, weight = 1},
        {id = 43, weight = 1},
        {id = 44, weight = 1},
        {id = 45, weight = 1},
        {id = 46, weight = 1},
        {id = 47, weight = 1},
        {id = 48, weight = 1},
        {id = 49, weight = .5},
        {id = 50, weight = .25}
	},
	[RoomType.ROOM_CHALLENGE] = {
        {id = 0, weight = 1},
        {id = 1, weight = 1},
        {id = 2, weight = 1},
        {id = 3, weight = 1},
        {id = 4, weight = 1},
        {id = 5, weight = .5},
        {id = 6, weight = 1},
        {id = 7, weight = .5},
        {id = 8, weight = .5},
        {id = 9, weight = .5},
        {id = 10, weight = .5},
        {id = 11, weight = .1},
        {id = 12, weight = .5},
        {id = 13, weight = .1},
        {id = 14, weight = .25},
        {id = 15, weight = .5},
        {id = 16, weight = 1},
        {id = 17, weight = 1},
        {id = 18, weight = 1},
        {id = 19, weight = 1},
        {id = 20, weight = 1},
        {id = 21, weight = 1},
        {id = 22, weight = .5},
        {id = 23, weight = .1},
        {id = 24, weight = .75}
	},
	[RoomType.ROOM_LIBRARY] = {
        {id = 0, weight = 1},
        {id = 1, weight = 1},
        {id = 2, weight = 1},
        {id = 3, weight = 1},
        {id = 4, weight = 1},
        {id = 5, weight = 1},
        {id = 6, weight = 1},
        {id = 7, weight = 1},
        {id = 8, weight = .25},
        {id = 9, weight = .5},
        {id = 10, weight = .5},
        {id = 11, weight = .5},
        {id = 12, weight = .25},
        {id = 13, weight = 1},
        {id = 14, weight = .5}
	},
	[RoomType.ROOM_SACRIFICE] = {
        {id = 0, weight = 1},
        {id = 1, weight = 1},
        {id = 2, weight = 1},
        {id = 3, weight = 1},
        {id = 4, weight = 1},
        {id = 5, weight = 1},
        {id = 6, weight = 1},
        {id = 7, weight = 1},
        {id = 8, weight = .5},
        {id = 9, weight = .1},
        {id = 10, weight = 1},
        {id = 11, weight = 1},
	},
	[RoomType.ROOM_ISAACS] = {
        {id = 0, weight = 1},
        {id = 1, weight = 1},
        {id = 2, weight = 1},
        {id = 3, weight = 1},
        {id = 4, weight = 1},
        {id = 5, weight = 1},
        {id = 6, weight = 1},
        {id = 7, weight = 1},
        {id = 8, weight = 1},
        {id = 9, weight = 1},
        {id = 10, weight = 1},
        {id = 11, weight = 1},
        {id = 12, weight = 1},
        {id = 13, weight = 1},
        {id = 14, weight = 1},
        {id = 15, weight = 1},
        {id = 16, weight = 1},
        {id = 17, weight = 1},
        {id = 18, weight = 1},
        {id = 19, weight = .25},
        {id = 20, weight = .1},
        {id = 21, weight = .1},
        {id = 22, weight = .1},
        {id = 23, weight = .5},
        {id = 24, weight = .25}
    },
    [RoomType.ROOM_BARREN] = {
        {id = 0, weight = 1},
        {id = 1, weight = 1},
        {id = 2, weight = 1},
        {id = 3, weight = 1},
        {id = 4, weight = 1},
        {id = 5, weight = 1},
        {id = 6, weight = 1},
        {id = 7, weight = 1},
        {id = 8, weight = 1},
        {id = 9, weight = 1},
        {id = 10, weight = 1},
        {id = 11, weight = 1},
        {id = 12, weight = 1},
        {id = 13, weight = 1},
        {id = 14, weight = 1},
        {id = 15, weight = 1},
        {id = 16, weight = 1},
        {id = 17, weight = 1},
        {id = 18, weight = 1},
        {id = 19, weight = .25},
        {id = 20, weight = .1},
        {id = 21, weight = .1},
        {id = 22, weight = .5},
        {id = 23, weight = .5},
        {id = 24, weight = .1}
    },
    [RoomType.ROOM_CHEST] = {
        {id = 0, weight = 1},
        {id = 1, weight = 1},
        {id = 2, weight = 1},
        {id = 3, weight = 1},
        {id = 4, weight = 1},
        {id = 5, weight = 1},
        {id = 6, weight = 1},
        {id = 7, weight = 1},
        {id = 8, weight = 1},
        {id = 9, weight = 1},
        {id = 10, weight = 1},
        {id = 11, weight = 1},
        {id = 12, weight = 1},
        {id = 13, weight = 1},
        {id = 14, weight = 1},
        {id = 15, weight = 1},
        {id = 16, weight = 1},
        {id = 17, weight = 1},
        {id = 18, weight = 1},
        {id = 19, weight = 1},
        {id = 20, weight = 1},
        {id = 21, weight = 1},
        {id = 22, weight = 1},
        {id = 23, weight = 1},
        {id = 24, weight = 1},
        {id = 25, weight = 1},
        {id = 26, weight = 1},
        {id = 27, weight = 1},
        {id = 28, weight = 1},
        {id = 29, weight = 1},
        {id = 30, weight = 1},
        {id = 31, weight = 1},
        {id = 32, weight = .75},
        {id = 33, weight = 1},
        {id = 34, weight = 1},
        {id = 35, weight = 1},
        {id = 36, weight = 1},
        {id = 37, weight = 1},
        {id = 38, weight = 1},
        {id = 39, weight = 1},
        {id = 40, weight = .1},
        {id = 41, weight = .1},
        {id = 42, weight = .75},
        {id = 43, weight = .75},
        {id = 44, weight = .5},
        {id = 45, weight = 1},
        {id = 46, weight = .25},
        {id = 47, weight = 1},
        {id = 48, weight = 1}
    },
    [RoomType.ROOM_DICE] = {
        {id = 0, weight = 1},
        {id = 1, weight = 1},
        {id = 2, weight = 1},
        {id = 3, weight = 1},
        {id = 4, weight = 1},
        {id = 5, weight = 1},
        {id = 6, weight = 1},
        {id = 7, weight = 1},
        {id = 8, weight = 1},
        {id = 9, weight = 1},
        {id = 10, weight = 1},
        {id = 11, weight = 1},
        {id = 12, weight = 1},
        {id = 13, weight = 1},
        {id = 14, weight = 1},
        {id = 15, weight = 1},
        {id = 16, weight = 1},
        {id = 17, weight = 1},
        {id = 18, weight = 1}
    },
    [RoomType.ROOM_PLANETARIUM] = {
        {id = 0, weight = 1},
        {id = 1, weight = 1},
        {id = 2, weight = 1},
        {id = 3, weight = .5},
        {id = 4, weight = .25}
    }
}
